name: trip_mate
description: Aplikasi Open Trip untuk menghubungkan Traveler dan Organizer.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.6.0          # WAJIB untuk API
  google_fonts: ^6.1.0  # WAJIB untuk font Poppins
  # Firebase & Google Sign-In
  firebase_core: ^3.8.0
  firebase_auth: ^5.5.0
  google_sign_in: ^6.3.0

  # Provider (WAJIB untuk tugas besar)
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true