// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCegSFCjd81-lnLuI2NVHVFLU3sbOThoBw',
    appId: '1:109753263296:web:9f492d8349e9e7e413b925',
    messagingSenderId: '109753263296',
    projectId: 'tripmate-project-fae1a',
    authDomain: 'tripmate-project-fae1a.firebaseapp.com',
    storageBucket: 'tripmate-project-fae1a.firebasestorage.app',
    measurementId: 'G-QE0D156EMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhlfr_CZdmQXwiGquWp3oMRBhUanWfucY',
    appId: '1:109753263296:android:7eb2d5ad0f65c69d13b925',
    messagingSenderId: '109753263296',
    projectId: 'tripmate-project-fae1a',
    storageBucket: 'tripmate-project-fae1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6d53UqycWeLrfP0pAFk3zznYHgNCy6XQ',
    appId: '1:109753263296:ios:2ff450a113c735c813b925',
    messagingSenderId: '109753263296',
    projectId: 'tripmate-project-fae1a',
    storageBucket: 'tripmate-project-fae1a.firebasestorage.app',
    androidClientId: '109753263296-g7t49ldvljjn4f4qe333r34n772ufglp.apps.googleusercontent.com',
    iosClientId: '109753263296-hhkcq8d4m5ok07jfo8h6uemednhm8n48.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesPpbApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6d53UqycWeLrfP0pAFk3zznYHgNCy6XQ',
    appId: '1:109753263296:ios:2ff450a113c735c813b925',
    messagingSenderId: '109753263296',
    projectId: 'tripmate-project-fae1a',
    storageBucket: 'tripmate-project-fae1a.firebasestorage.app',
    androidClientId: '109753263296-g7t49ldvljjn4f4qe333r34n772ufglp.apps.googleusercontent.com',
    iosClientId: '109753263296-hhkcq8d4m5ok07jfo8h6uemednhm8n48.apps.googleusercontent.com',
    iosBundleId: 'com.example.tubesPpbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCegSFCjd81-lnLuI2NVHVFLU3sbOThoBw',
    appId: '1:109753263296:web:79526118d1b5f42413b925',
    messagingSenderId: '109753263296',
    projectId: 'tripmate-project-fae1a',
    authDomain: 'tripmate-project-fae1a.firebaseapp.com',
    storageBucket: 'tripmate-project-fae1a.firebasestorage.app',
    measurementId: 'G-9TQ2927Q59',
  );
}
